@startuml
'https://plantuml.com/class-diagram

class Solution41{
SortNames application = new SortNames()
}

class SortNames {
+void scanInputFile(): List<String>
+void sortList(unsortedList: List<String>)
+void printToOutputFile(sortedList: List<String>)
}

Solution41 - SortNames

@enduml